class_name CardData
extends Node

const card = {
	0:{"name":"CharroudFullArt", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof.png", "estUnique":true},
	1:{"name":"Charroud", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (2).png", "estUnique":true},
	2:{"name":"Tran Minh", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (3).png", "estUnique":true},
	3:{"name":"Crespy", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (4).png", "estUnique":true},
	4:{"name":"Guilloton", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (5).png", "estUnique":true},
	5:{"name":"Guisse", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (6).png", "estUnique":true},
	6:{"name":"Dehay", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (7).png", "estUnique":true},
	7:{"name":"Pasha", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (8).png", "estUnique":true},
	8:{"name":"Deleuze", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (9).png", "estUnique":true},
	9:{"name":"Giorgi", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (10).png", "estUnique":true},
	10:{"name":"Barbot", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (11).png", "estUnique":true},
	11:{"name":"Toupance", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (12).png", "estUnique":true},
	12:{"name":"Céline Jeanne", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (13).png", "estUnique":true},
	13:{"name":"Mendes", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (14).png", "estUnique":true},
	14:{"name":"Hely", "type":Card.CardType.PROF, "done":false, "file":"res://assets/cards/Prof (15).png", "estUnique":true},
	15:{"name":"Modulation", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action.png", "estUnique":false},
	16:{"name":"Thevenin/Norton", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (2).png", "estUnique":false},
	17:{"name":"Abaque de Smith", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (5).png", "estUnique":false},
	18:{"name":"Bode", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (7).png", "estUnique":false},
	19:{"name":"Protocole tcp/ip", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (8).png", "estUnique":false},
	20:{"name":"Tri à bulles", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (9).png", "estUnique":false},
	21:{"name":"Avé les mimines", "type":Card.CardType.ACTION, "cout":6, "done":false, "file":"res://assets/cards/Action (10).png", "estUnique":true},
	22:{"name":"0/0 explosion", "type":Card.CardType.ACTION, "cout":10, "done":false, "file":"res://assets/cards/Action (11).png", "estUnique":true},
	23:{"name":"Série de Taylor", "type":Card.CardType.ACTION, "cout":6, "done":false, "file":"res://assets/cards/Action (12).png", "estUnique":true},
	24:{"name":"Décomposition en éléments simples", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (13).png", "estUnique":false},
	25:{"name":"Chaîne de Markov", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (14).png", "estUnique":false},
	26:{"name":"Preuve", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (15).png", "estUnique":false},
	27:{"name":"Équivalence", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (17).png", "estUnique":false},
	28:{"name":"Chamilo", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (18).png", "estUnique":false},
	29:{"name":"Révision intensive", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (21).png", "estUnique":false},
	30:{"name":"Partiel", "type":Card.CardType.ACTION, "cout":-1, "done":false, "file":"res://assets/cards/Action (22).png", "estUnique":false},
	31:{"name":"Rattrapage", "type":Card.CardType.ACTION, "cout":-1, "done":false, "file":"res://assets/cards/Action (23).png", "estUnique":false},
	32:{"name":"Plus de budget", "type":Card.CardType.ACTION, "cout":-1, "done":false, "file":"res://assets/cards/Action (25).png", "estUnique":false},
	33:{"name":"Compétition Robot Sumo", "type":Card.CardType.ACTION, "cout":5, "done":false, "file":"res://assets/cards/Action (26).png", "estUnique":false},
	34:{"name":"Soirée Visionnage", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (27).png", "estUnique":false},
	35:{"name":"Concours de dessin", "type":Card.CardType.ACTION, "cout":5, "done":false, "file":"res://assets/cards/Action (28).png", "estUnique":false},
	36:{"name":"Scène ouverte", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (29).png", "estUnique":false},
	37:{"name":"Coup de batte", "type":Card.CardType.ACTION, "cout":2, "done":false, "file":"res://assets/cards/Action (30).png", "estUnique":false},
	38:{"name":"Rime en -é", "type":Card.CardType.ACTION, "cout":2, "done":false, "file":"res://assets/cards/Action (32).png", "estUnique":false},
	39:{"name":"Weekend ski", "type":Card.CardType.ACTION, "cout":6, "done":false, "file":"res://assets/cards/Action (33).png", "estUnique":false},
	40:{"name":"Patinoire sport nat", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (34).png", "estUnique":false},
	41:{"name":"Esijam", "type":Card.CardType.ACTION, "cout":2, "done":false, "file":"res://assets/cards/Action (35).png", "estUnique":false},
	42:{"name":"Session de partage", "type":Card.CardType.ACTION, "cout":7, "done":false, "file":"res://assets/cards/Action (36).png", "estUnique":false},
	43:{"name":"LANalyse", "type":Card.CardType.ACTION, "cout":5, "done":false, "file":"res://assets/cards/Action (37).png", "estUnique":false},
	44:{"name":"reLANce", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (38).png", "estUnique":false},
	45:{"name":"LANterrement", "type":Card.CardType.ACTION, "cout":6, "done":false, "file":"res://assets/cards/Action (39).png", "estUnique":false},
	46:{"name":"LANnexion", "type":Card.CardType.ACTION, "cout":6, "done":false, "file":"res://assets/cards/Action (40).png", "estUnique":false},
	47:{"name":"Antistress", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (41).png", "estUnique":false},
	48:{"name":"CSAW", "type":Card.CardType.ACTION, "cout":9, "done":false, "file":"res://assets/cards/Action (42).png", "estUnique":true},
	49:{"name":"Décryptage", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (43).png", "estUnique":false},
	50:{"name":"Cryptage", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (46).png", "estUnique":false},
	51:{"name":"Session 0", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (47).png", "estUnique":false},
	52:{"name":"Brute Force", "type":Card.CardType.ACTION, "cout":6, "done":false, "file":"res://assets/cards/Action (48).png", "estUnique":true},
	53:{"name":"Inventaire", "type":Card.CardType.ACTION, "cout":5, "done":false, "file":"res://assets/cards/Action (49).png", "estUnique":false},
	54:{"name":"Weekend d'intégration", "type":Card.CardType.ACTION, "cout":9, "done":false, "file":"res://assets/cards/Action (50).png", "estUnique":true},
	55:{"name":"Réveil Sport Nat", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (51).png", "estUnique":false},
	56:{"name":"PLS", "type":Card.CardType.ACTION, "cout":2, "done":false, "file":"res://assets/cards/Action (52).png", "estUnique":false},
	57:{"name":"Gala", "type":Card.CardType.ACTION, "cout":7, "done":false, "file":"res://assets/cards/Action (54).png", "estUnique":true},
	58:{"name":"PFE", "type":Card.CardType.ACTION, "cout":5, "done":false, "file":"res://assets/cards/Action (55).png", "estUnique":false},
	59:{"name":"Projet industriel", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (56).png", "estUnique":false},
	60:{"name":"Challenge", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (57).png", "estUnique":false},
	61:{"name":"Coupure de courant", "type":Card.CardType.ACTION, "cout":3, "done":false, "file":"res://assets/cards/Action (58).png", "estUnique":false},
	62:{"name":"Alarme incendie", "type":Card.CardType.ACTION, "cout":7, "done":false, "file":"res://assets/cards/Action (59).png", "estUnique":false},
	63:{"name":"P'tit remontant", "type":Card.CardType.ACTION, "cout":6, "done":false, "file":"res://assets/cards/Action (60).png", "estUnique":false},
	64:{"name":"Cuck le fercle", "type":Card.CardType.ACTION, "cout":0, "done":false, "file":"res://assets/cards/Action (61).png", "estUnique":false},
	65:{"name":"Banni", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (63).png", "estUnique":false},
	66:{"name":"Rangée de Q", "type":Card.CardType.ACTION, "cout":4, "done":false, "file":"res://assets/cards/Action (65).png", "estUnique":false},
	67:{"name":"Membre CIE", "type":Card.CardType.ESISARIEN, "cout":3, "atk":1, "def":3, "done":false, "file":"res://assets/cards/Esisarien.png", "estUnique":false},
	68:{"name":"VP CIE", "type":Card.CardType.ESISARIEN, "cout":4, "atk":3, "def":3, "done":false, "file":"res://assets/cards/Esisarien (2).png", "estUnique":false},
	69:{"name":"Respo Com CIE", "type":Card.CardType.ESISARIEN, "cout":4, "atk":1, "def":4, "done":false, "file":"res://assets/cards/Esisarien (3).png", "estUnique":false},
	70:{"name":"Trésorier CIE", "type":Card.CardType.ESISARIEN, "cout":5, "atk":2, "def":4, "done":false, "file":"res://assets/cards/Esisarien (4).png", "estUnique":false},
	71:{"name":"Président CIE", "type":Card.CardType.ESISARIEN, "cout":6, "atk":1, "def":6, "done":false, "file":"res://assets/cards/Esisarien (5).png", "estUnique":true},
	72:{"name":"Erwan", "type":Card.CardType.ESISARIEN, "cout":6, "atk":4, "def":4, "done":false, "file":"res://assets/cards/Esisarien (6).png", "estUnique":true},
	73:{"name":"Membre Sport Nat", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":3, "done":false, "file":"res://assets/cards/Esisarien (7).png", "estUnique":false},
	74:{"name":"Trésorier Sport Nat", "type":Card.CardType.ESISARIEN, "cout":5, "atk":5, "def":3, "done":false, "file":"res://assets/cards/Esisarien (9).png", "estUnique":false},
	75:{"name":"Président Sport Nat", "type":Card.CardType.ESISARIEN, "cout":6, "atk":8, "def":3, "done":false, "file":"res://assets/cards/Esisarien (10).png", "estUnique":true},
	76:{"name":"Membre Esiglisse", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":1, "done":false, "file":"res://assets/cards/Esisarien (11).png", "estUnique":false},
	77:{"name":"Trésorier Esiglisse", "type":Card.CardType.ESISARIEN, "cout":5, "atk":4, "def":2, "done":false, "file":"res://assets/cards/Esisarien (12).png", "estUnique":false},
	78:{"name":"Président Esiglisse", "type":Card.CardType.ESISARIEN, "cout":6, "atk":5, "def":4, "done":false, "file":"res://assets/cards/Esisarien (13).png", "estUnique":true},
	79:{"name":"Membre CRE", "type":Card.CardType.ESISARIEN, "cout":3, "atk":2, "def":2, "done":false, "file":"res://assets/cards/Esisarien (14).png", "estUnique":false},
	80:{"name":"Respo Projet CRE", "type":Card.CardType.ESISARIEN, "cout":4, "atk":3, "def":3, "done":false, "file":"res://assets/cards/Esisarien (15).png", "estUnique":false},
	81:{"name":"Respo Com CRE", "type":Card.CardType.ESISARIEN, "cout":4, "atk":4, "def":2, "done":false, "file":"res://assets/cards/Esisarien (17).png", "estUnique":false},
	82:{"name":"Trésorier CRE", "type":Card.CardType.ESISARIEN, "cout":5, "atk":2, "def":5, "done":false, "file":"res://assets/cards/Esisarien (18).png", "estUnique":false},
	83:{"name":"Président CRE", "type":Card.CardType.ESISARIEN, "cout":6, "atk":2, "def":4, "done":false, "file":"res://assets/cards/Esisarien (19).png", "estUnique":true},
	84:{"name":"Membre Krhacken", "type":Card.CardType.ESISARIEN, "cout":3, "atk":1, "def":2, "done":false, "file":"res://assets/cards/Esisarien (20).png", "estUnique":false},
	85:{"name":"Respo Com Krhacken", "type":Card.CardType.ESISARIEN, "cout":4, "atk":3, "def":2, "done":false, "file":"res://assets/cards/Esisarien (22).png", "estUnique":false},
	86:{"name":"Trésorier Krhacken", "type":Card.CardType.ESISARIEN, "cout":5, "atk":4, "def":2, "done":false, "file":"res://assets/cards/Esisarien (23).png", "estUnique":false},
	87:{"name":"Président Krhacken", "type":Card.CardType.ESISARIEN, "cout":5, "atk":2, "def":4, "done":false, "file":"res://assets/cards/Esisarien (24).png", "estUnique":true},
	88:{"name":"Membre Esidraw", "type":Card.CardType.ESISARIEN, "cout":3, "atk":2, "def":2, "done":false, "file":"res://assets/cards/Esisarien (25).png", "estUnique":false},
	89:{"name":"Respo Com Esidraw", "type":Card.CardType.ESISARIEN, "cout":4, "atk":2, "def":4, "done":false, "file":"res://assets/cards/Esisarien (26).png", "estUnique":false},
	90:{"name":"Trésorier Esidraw", "type":Card.CardType.ESISARIEN, "cout":5, "atk":3, "def":3, "done":false, "file":"res://assets/cards/Esisarien (29).png", "estUnique":false},
	91:{"name":"Président Esidraw", "type":Card.CardType.ESISARIEN, "cout":6, "atk":3, "def":6, "done":false, "file":"res://assets/cards/Esisarien (30).png", "estUnique":true},
	92:{"name":"Membre Musisar", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":1, "done":false, "file":"res://assets/cards/Esisarien (32).png", "estUnique":false},
	93:{"name":"DJ Musisar", "type":Card.CardType.ESISARIEN, "cout":4, "atk":2, "def":3, "done":false, "file":"res://assets/cards/Esisarien (33).png", "estUnique":false},
	94:{"name":"Rappeur Musisar", "type":Card.CardType.ESISARIEN, "cout":4, "atk":3, "def":2, "done":false, "file":"res://assets/cards/Esisarien (34).png", "estUnique":false},
	95:{"name":"Trésorier Musisar", "type":Card.CardType.ESISARIEN, "cout":5, "atk":2, "def":3, "done":false, "file":"res://assets/cards/Esisarien (35).png", "estUnique":false},
	96:{"name":"Président Musisar", "type":Card.CardType.ESISARIEN, "cout":6, "atk":4, "def":5, "done":false, "file":"res://assets/cards/Esisarien (36).png", "estUnique":true},
	97:{"name":"Membre cercle", "type":Card.CardType.ESISARIEN, "cout":4, "atk":3, "def":3, "done":false, "file":"res://assets/cards/Esisarien (37).png", "estUnique":false},
	98:{"name":"Respo Club Cercle", "type":Card.CardType.ESISARIEN, "cout":6, "atk":3, "def":4, "done":false, "file":"res://assets/cards/Esisarien (39).png", "estUnique":false},
	99:{"name":"Secrétaire Cercle", "type":Card.CardType.ESISARIEN, "cout":6, "atk":2, "def":4, "done":false, "file":"res://assets/cards/Esisarien (40).png", "estUnique":false},
	100:{"name":"Trésorier Cercle", "type":Card.CardType.ESISARIEN, "cout":6, "atk":2, "def":5, "done":false, "file":"res://assets/cards/Esisarien (41).png", "estUnique":false},
	101:{"name":"Respo part Cercle", "type":Card.CardType.ESISARIEN, "cout":4, "atk":1, "def":4, "done":false, "file":"res://assets/cards/Esisarien (42).png", "estUnique":false},
	102:{"name":"Président Cercle", "type":Card.CardType.ESISARIEN, "cout":7, "atk":5, "def":5, "done":false, "file":"res://assets/cards/Esisarien (43).png", "estUnique":true},
	103:{"name":"Membre AVE", "type":Card.CardType.ESISARIEN, "cout":6, "atk":5, "def":5, "done":false, "file":"res://assets/cards/Esisarien (44).png", "estUnique":true},
	104:{"name":"Personne", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":0, "done":false, "file":"res://assets/cards/Esisarien (46).png", "estUnique":false},
	105:{"name":"Bandana blanc", "type":Card.CardType.ESISARIEN, "cout":5, "atk":4, "def":4, "done":false, "file":"res://assets/cards/Esisarien (47).png", "estUnique":false},
	106:{"name":"Bandana rouge", "type":Card.CardType.ESISARIEN, "cout":5, "atk":4, "def":4, "done":false, "file":"res://assets/cards/Esisarien (48).png", "estUnique":false},
	107:{"name":"Étudiant Bienveillant", "type":Card.CardType.ESISARIEN, "cout":4, "atk":1, "def":3, "done":false, "file":"res://assets/cards/Esisarien (49).png", "estUnique":false},
	108:{"name":"Étudiant Malveillant", "type":Card.CardType.ESISARIEN, "cout":4, "atk":3, "def":1, "done":false, "file":"res://assets/cards/Esisarien (50).png", "estUnique":false},
	109:{"name":"Étudiant Fêtard", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":2, "done":false, "file":"res://assets/cards/Esisarien (51).png", "estUnique":false},
	110:{"name":"Étudiant Timide", "type":Card.CardType.ESISARIEN, "cout":2, "atk":1, "def":3, "done":false, "file":"res://assets/cards/Esisarien (52).png", "estUnique":false},
	111:{"name":"Étudiant Procrastinateur", "type":Card.CardType.ESISARIEN, "cout":2, "atk":0, "def":3, "done":false, "file":"res://assets/cards/Esisarien (53).png", "estUnique":false},
	112:{"name":"Étudiant Rageux", "type":Card.CardType.ESISARIEN, "cout":4, "atk":4, "def":1, "done":false, "file":"res://assets/cards/Esisarien (54).png", "estUnique":false},
	113:{"name":"Étudiant Stressé", "type":Card.CardType.ESISARIEN, "cout":1, "atk":0, "def":2, "done":false, "file":"res://assets/cards/Esisarien (55).png", "estUnique":false},
	114:{"name":"Étudiant Discret", "type":Card.CardType.ESISARIEN, "cout":1, "atk":2, "def":0, "done":false, "file":"res://assets/cards/Esisarien (56).png", "estUnique":false},
	115:{"name":"Étudiant Pressé", "type":Card.CardType.ESISARIEN, "cout":2, "atk":2, "def":0, "done":false, "file":"res://assets/cards/Esisarien (57).png", "estUnique":false},
	116:{"name":"Étudiant Charmant", "type":Card.CardType.ESISARIEN, "cout":2, "atk":1, "def":2, "done":false, "file":"res://assets/cards/Esisarien (58).png", "estUnique":false},
	117:{"name":"Étudiant Inventif", "type":Card.CardType.ESISARIEN, "cout":1, "atk":1, "def":1, "done":false, "file":"res://assets/cards/Esisarien (59).png", "estUnique":false},
	118:{"name":"Étudiant Génial", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":1, "done":false, "file":"res://assets/cards/Esisarien (60).png", "estUnique":false},
	119:{"name":"Étudiant Studieux", "type":Card.CardType.ESISARIEN, "cout":3, "atk":0, "def":4, "done":false, "file":"res://assets/cards/Esisarien (61).png", "estUnique":false},
	120:{"name":"Étudiant Prépa Intégrée", "type":Card.CardType.ESISARIEN, "cout":2, "atk":1, "def":1, "done":false, "file":"res://assets/cards/Esisarien (62).png", "estUnique":false},
	121:{"name":"Étudiant CPGE", "type":Card.CardType.ESISARIEN, "cout":2, "atk":1, "def":1, "done":false, "file":"res://assets/cards/Esisarien (65).png", "estUnique":false},
	122:{"name":"Étudiant Info", "type":Card.CardType.ESISARIEN, "cout":3, "atk":2, "def":3, "done":false, "file":"res://assets/cards/Esisarien (67).png", "estUnique":false},
	123:{"name":"Étudiant Élec", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":2, "done":false, "file":"res://assets/cards/Esisarien (69).png", "estUnique":false},
	124:{"name":"Étudiant Apprentis", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":1, "done":false, "file":"res://assets/cards/Esisarien (70).png", "estUnique":false},
	125:{"name":"CPP", "type":Card.CardType.ESISARIEN, "cout":4, "atk":1, "def":3, "done":false, "file":"res://assets/cards/Esisarien (71).png", "estUnique":false},
	126:{"name":"IUTien", "type":Card.CardType.ESISARIEN, "cout":3, "atk":3, "def":0, "done":false, "file":"res://assets/cards/Esisarien (72).png", "estUnique":false},
	127:{"name":"Poulpy Vampire", "type":Card.CardType.ESISARIEN, "cout":6, "atk":6, "def":0, "done":false, "file":"res://assets/cards/Esisarien (73).png", "estUnique":true},
	128:{"name":"Poulpy Batman", "type":Card.CardType.ESISARIEN, "cout":5, "atk":4, "def":4, "done":false, "file":"res://assets/cards/Esisarien (74).png", "estUnique":true},
	129:{"name":"Poulpy SNCF", "type":Card.CardType.ESISARIEN, "cout":5, "atk":2, "def":5, "done":false, "file":"res://assets/cards/Esisarien (75).png", "estUnique":true},
	130:{"name":"Poulpy 20000 lieux sous les mers", "type":Card.CardType.ESISARIEN, "cout":5, "atk":3, "def":2, "done":false, "file":"res://assets/cards/Esisarien (76).png", "estUnique":true},
	131:{"name":"Poulpy Reine des neiges", "type":Card.CardType.ESISARIEN, "cout":5, "atk":2, "def":6, "done":false, "file":"res://assets/cards/Esisarien (77).png", "estUnique":true},
	132:{"name":"Poulpy mineur", "type":Card.CardType.ESISARIEN, "cout":5, "atk":3, "def":5, "done":false, "file":"res://assets/cards/Esisarien (78).png", "estUnique":true},
	133:{"name":"Poulpy Mad Max", "type":Card.CardType.ESISARIEN, "cout":5, "atk":5, "def":1, "done":false, "file":"res://assets/cards/Esisarien (79).png", "estUnique":true},
	134:{"name":"Poulpy Retraité", "type":Card.CardType.ESISARIEN, "cout":5, "atk":1, "def":1, "done":false, "file":"res://assets/cards/Esisarien (80).png", "estUnique":true},
	135:{"name":"Poulpy Zoo", "type":Card.CardType.ESISARIEN, "cout":5, "atk":5, "def":2, "done":false, "file":"res://assets/cards/Esisarien (81).png", "estUnique":true},
	136:{"name":"Tank", "type":Card.CardType.ESISARIEN, "cout":10, "atk":10, "def":10, "done":false, "file":"res://assets/cards/Esisarien (82).png", "estUnique":true},
	137:{"name":"Poulpy", "type":Card.CardType.ESISARIEN, "cout":8, "atk":8, "def":8, "done":false, "file":"res://assets/cards/Esisarien (83).png", "estUnique":true},
	138:{"name":"Machine de Turing", "type":Card.CardType.OBJET, "cout":7, "done":false, "file":"res://assets/cards/Objet.png", "estUnique":true},
	139:{"name":"Terminal", "type":Card.CardType.OBJET, "cout":8, "done":false, "file":"res://assets/cards/Objet (2).png", "estUnique":true},
	140:{"name":"Serveur HTTP", "type":Card.CardType.OBJET, "cout":4, "done":false, "file":"res://assets/cards/Objet (3).png", "estUnique":false},
	141:{"name":"NAT", "type":Card.CardType.OBJET, "cout":5, "done":false, "file":"res://assets/cards/Objet (4).png", "estUnique":false},
	142:{"name":"Routeur", "type":Card.CardType.OBJET, "cout":4, "done":false, "file":"res://assets/cards/Objet (5).png", "estUnique":false},
	143:{"name":"Peluche Poulpix", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (6).png", "estUnique":false},
	144:{"name":"Peluche Poulpix", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (7).png", "estUnique":false},
	145:{"name":"Crêpière", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (8).png", "estUnique":false},
	146:{"name":"Crêpe", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (10).png", "estUnique":false},
	147:{"name":"Borne D'arcade", "type":Card.CardType.OBJET, "cout":6, "done":false, "file":"res://assets/cards/Objet (11).png", "estUnique":false},
	148:{"name":"Robot Bar Challenge", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (12).png", "estUnique":false},
	149:{"name":"Robot Sumo", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (13).png", "estUnique":false},
	150:{"name":"Drone Load", "type":Card.CardType.OBJET, "cout":-1, "done":false, "file":"res://assets/cards/Objet (15).png", "estUnique":false},
	151:{"name":"Cansat", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (16).png", "estUnique":false},
	152:{"name":"Formule 1", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (17).png", "estUnique":false},
	153:{"name":"Condensateur", "type":Card.CardType.OBJET, "cout":4, "done":false, "file":"res://assets/cards/Objet (18).png", "estUnique":false},
	154:{"name":"Bobine", "type":Card.CardType.OBJET, "cout":5, "done":false, "file":"res://assets/cards/Objet (19).png", "estUnique":false},
	155:{"name":"Carte Électronique", "type":Card.CardType.OBJET, "cout":5, "done":false, "file":"res://assets/cards/Objet (20).png", "estUnique":false},
	156:{"name":"AOP sommateur", "type":Card.CardType.OBJET, "cout":7, "done":false, "file":"res://assets/cards/Objet (21).png", "estUnique":true},
	157:{"name":"AOP montage suiveur", "type":Card.CardType.OBJET, "cout":4, "done":false, "file":"res://assets/cards/Objet (22).png", "estUnique":false},
	158:{"name":"Filtre passe haut", "type":Card.CardType.OBJET, "cout":6, "done":false, "file":"res://assets/cards/Objet (23).png", "estUnique":true},
	159:{"name":"Filtre passe bas", "type":Card.CardType.OBJET, "cout":6, "done":false, "file":"res://assets/cards/Objet (24).png", "estUnique":true},
	160:{"name":"Soundboks", "type":Card.CardType.OBJET, "cout":4, "done":false, "file":"res://assets/cards/Objet (25).png", "estUnique":false},
	161:{"name":"Lumières", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (26).png", "estUnique":false},
	162:{"name":"Table de mixage", "type":Card.CardType.OBJET, "cout":6, "done":false, "file":"res://assets/cards/Objet (27).png", "estUnique":true},
	163:{"name":"Micro", "type":Card.CardType.OBJET, "cout":4, "done":false, "file":"res://assets/cards/Objet (28).png", "estUnique":false},
	164:{"name":"Enceinte", "type":Card.CardType.OBJET, "cout":5, "done":false, "file":"res://assets/cards/Objet (29).png", "estUnique":false},
	165:{"name":"Instruments", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (31).png", "estUnique":false},
	166:{"name":"Dessin", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (33).png", "estUnique":false},
	167:{"name":"Flasque", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (35).png", "estUnique":false},
	168:{"name":"Raclette", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (36).png", "estUnique":false},
	169:{"name":"Ballon de volley", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (37).png", "estUnique":false},
	170:{"name":"Tente", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (39).png", "estUnique":false},
	171:{"name":"Panier de légumes", "type":Card.CardType.OBJET, "cout":4, "done":false, "file":"res://assets/cards/Objet (40).png", "estUnique":false},
	172:{"name":"Dégaine d'escalade", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (42).png", "estUnique":false},
	173:{"name":"Carte Esiclash", "type":Card.CardType.OBJET, "cout":5, "done":false, "file":"res://assets/cards/Objet (43).png", "estUnique":false},
	174:{"name":"Carte Nobody", "type":Card.CardType.OBJET, "cout":4, "done":false, "file":"res://assets/cards/Objet (44).png", "estUnique":false},
	175:{"name":"Red Bull", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (45).png", "estUnique":false},
	176:{"name":"Caddie", "type":Card.CardType.OBJET, "cout":5, "done":false, "file":"res://assets/cards/Objet (47).png", "estUnique":false},
	177:{"name":"Lance", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (48).png", "estUnique":false},
	178:{"name":"Pioche", "type":Card.CardType.OBJET, "cout":3, "done":false, "file":"res://assets/cards/Objet (49).png", "estUnique":false},
	179:{"name":"Alcool", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (50).png", "estUnique":false},
	180:{"name":"Porte", "type":Card.CardType.OBJET, "cout":2, "done":false, "file":"res://assets/cards/Objet (52).png", "estUnique":false},
}
